### ISSUE TITLE
[Feature Request]: Links in Certificate

### ISSUE THREAD

**Issue by AnshumanDubey1999** [open-certs/oc-backend#10]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

Have links associated with all icons for easy access to relevant webpages

### Proposed Solution

surround image tags with anchor tags that contains links to corresponding webpages

### Alternatives Considered

None

**Comment by Kanika1309** [comment]
Hi...I am GSSoC'22 participant if this task is still open....please assign it to me.

**Comment by Shubham-Kumar-2000** [comment]
@Kanika1309  There is already a PR regarding this.
