### ISSUE TITLE
[Feature Request]:  API to Fetch Certificate By ID

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#12]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

There is no API to fetch the certificate details based on certificate ID.

### Proposed Solution

Make a API to get certificate details based on Certificate ID.

### Alternatives Considered

NA

**Comment by SatabrataPaul-GitAc** [comment]
Hi I am Satabrata Paul , a participant of GSSOC'22 . I would like to work on this feature 
Can you assign it to me ?

**Comment by Shubham-Kumar-2000** [comment]
Assigned go ahead

**Comment by Karan11000** [comment]
HI I am Karan Dua, GSSOC'22 Participant. I would like to work on this issue. can you assign me on this issue?
