### ISSUE TITLE
[Bug]: Github Access tokens are visible using https://jwt.io/

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#13]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

If I try to decode the user-token using [JWT Decode](https://jwt.io/) . 

I get user's public data but along with it I also get the third-party Oauth Token.
This could cause potential vulnerability.

### Expected Behavior

Third-party Oauth Token should be stored in a encrypted way and can be decrypted while validating user-token.

### Additional Information

You may use https://www.npmjs.com/package/aes256

**Comment by rv602** [comment]
Hello @Shubham-Kumar-2000 , Rajagopalan this side.
I wish to work on this issue and learn about encryption, decryption and get started in backend.
I feel this will be a good addition to the project as well as my skillset.

**Comment by Shubham-Kumar-2000** [comment]
Assigned go ahead

**Comment by Shubham-Kumar-2000** [comment]
hi @rv602 any update on this??

**Comment by Shubham-Kumar-2000** [comment]
@rv602  what happened why did you unassigned your self?

**Comment by mdabdulshahed** [comment]
I want to work on this issue. please assign it to me

**Comment by Shubham-Kumar-2000** [comment]
Sure go ahead @mdabdulshahed

**Comment by Shubham-Kumar-2000** [comment]
Hi @mdabdulshahed  any update on this??

**Comment by Shubham-Kumar-2000** [comment]
Hi @mdabdulshahed  due to no response un-assigning you from this issue.

**Comment by MadhusreeBera** [comment]
Please assign this issue to me.

**Comment by Shubham-Kumar-2000** [comment]
Sure go ahead.
