### ISSUE TITLE
[Feature Request]: Updating readme regarding github client ID

### ISSUE THREAD

**Issue by himanshusanecha** [open-certs/oc-backend#14]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

Need documentation regarding generating Github client ID to be used in the open-certs backend.

### Proposed Solution

Writing a technical documentation regarding github client ID.

### Alternatives Considered

N/A

**Comment by himanshusanecha** [comment]
I am interested to work on this issue.

**Comment by Shubham-Kumar-2000** [comment]
@himanshusanecha  Please complete your assigned issue. Then re-comment to get assigned.

**Comment by himanshusanecha** [comment]
I am interested to work on this issue.

**Comment by Sumit-Anand3098** [comment]
I am interested to work on this issue.

**Comment by Sukh0204** [comment]
I'm Sukhman, participant of GSSoc'22. Please assign me this issue.

**Comment by Shubham-Kumar-2000** [comment]
Hi @Sukh0204  any update on this?

**Comment by amir-ammar** [comment]
@Shubham-Kumar-2000 can i work on it

**Comment by Sukh0204** [comment]
> Hi @Sukh0204  any update on this?

I'm working on it

**Comment by Shubham-Kumar-2000** [comment]
Closing this as this issue was solved under pr : #29
