### ISSUE TITLE
[Feature Request]: Validation for certificate creation request

### ISSUE THREAD

**Issue by AnshumanDubey1999** [open-certs/oc-backend#16]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

There is no validation for the post request, which contains  includeRepositoryImage and includeUserImage, and has boolean values.

### Proposed Solution

Add validation check so that their is no scope of misconfiguration of API in front-end.

### Alternatives Considered

None

**Comment by Simran2337** [comment]
I am interested to work on this issue as a GSSOC'22 participant.
Can you please assign it to me?
