### ISSUE TITLE
[Feature Request]: Global Error Handler with Custom Errors

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#17]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

We don't have a global error handler in the code base right now.

### Proposed Solution

Use proper error handler which can be replaced by default express error handler.

Also need all catch blocks to redirect to that error handler.

And have multiple error classes for different errors like validation error, Login Error, etc.

### Alternatives Considered

NA

**Comment by anipaul2** [comment]
Assign me this mentor @Shubham-Kumar-2000 ...Participant from gssoc'22

**Comment by Shubham-Kumar-2000** [comment]
Sure Assigned

**Comment by Shubham-Kumar-2000** [comment]
Hi @anipaul2  any update on this?

**Comment by anipaul2** [comment]
> Hi @anipaul2 any update on this?

Sorry mentor my exams will finish tomorrow and after that will give full time to it. Just give me two more days mentor.

**Comment by anipaul2** [comment]
> Hi @anipaul2 any update on this?

Will start from today, working on this mentor..Thanks for letting me do this till now.

**Comment by Shubham-Kumar-2000** [comment]
Hi @anipaul2  any update on this??

**Comment by anipaul2** [comment]
> Hi @anipaul2 any update on this??

Working on it. facing some issue so didn't raised a pr.

**Comment by anipaul2** [comment]
@Shubham-Kumar-2000 raised a pr. please review!
