### ISSUE TITLE
[Feature Request]: Gitlab Login

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#2]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

Gitlab Login doesn't exist but many open source softwares are still maintained on gitlab.
Thus gitlab should be supported.

### Proposed Solution

Use `passport-gitlab2` to integrate gitlab auth.

### Alternatives Considered

None

**Comment by Kanika1309** [comment]
Hi...I am GSSoC'22 participant if this task is still open....please assign it to me.

**Comment by Shubham-Kumar-2000** [comment]
@Kanika1309  Assigned to you but don't raise the PR before 1 March else it won't be counted

**Comment by SatabrataPaul-GitAc** [comment]
Hello I am a GSSOC'22 pariticipant . Please can you assign this task to me . I would like to make a contribution to this project

**Comment by Shubham-Kumar-2000** [comment]
hi @SatabrataPaul-GitAc  it is already assigned to @Kanika1309 .

@Kanika1309  what's the update on this issue?

**Comment by Kanika1309** [comment]
Hi @Shubham-Kumar-2000,  I am still working on it.  Can i let you know by monday if I will be able to complete it or not?

**Comment by Shubham-Kumar-2000** [comment]
If you need any help just ping in the discord channel. We are here to help

**Comment by Shubham-Kumar-2000** [comment]
@Kanika1309  Any update on this?

**Comment by Shubham-Kumar-2000** [comment]
@Kanika1309  assigning due to no response.

**Comment by amir-ammar** [comment]
@Shubham-Kumar-2000 can i work on it ?

**Comment by Shubham-Kumar-2000** [comment]
@amir-ammar Please complete your assigned issue then re-comment to get assigned

**Comment by SatabrataPaul-GitAc** [comment]
Hello Shubham 
Can you assign this issue to me 

I have completed my previous 2 assignments

**Comment by amir-ammar** [comment]
@Shubham-Kumar-2000 i have finish it, waiting for view PR

**Comment by Shubham-Kumar-2000** [comment]
@SatabrataPaul-GitAc  assigned go ahead
