### ISSUE TITLE
[Feature Request]: Add a unique Id in the certificate for verification.

### ISSUE THREAD

**Issue by Adi-11** [open-certs/oc-backend#20]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

For validating the authenticity of the certificate there is already a QR code in the certificate but for a more handly way for quick validation, we can also give unique IDs printed on the certificates, for one-click verification, on the website.

### Proposed Solution

Add a unique ID on the certificate maintaining the proper design, unique ID can be the Object ID of the certificate itself.

### Alternatives Considered

NA

### Additional Information

NA

**Comment by Simran2337** [comment]
I want to work on this issue as a GSSOC'22 participant @Adi-11
