### ISSUE TITLE
[Bug]: The MongoDB connection must be promisified

### ISSUE THREAD

**Issue by SatabrataPaul-GitAc** [open-certs/oc-backend#24]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

Event based mongoDB connection

### Expected Behavior

Promised based mongoDB connection

**Comment by SatabrataPaul-GitAc** [comment]
Please assign this issue to me . 
I have verified the bug and want to start working on it

**Comment by Shubham-Kumar-2000** [comment]
Assigned @SatabrataPaul-GitAc  go ahead.
