### ISSUE TITLE
[Bug]: Bitbucket Setup for Oauth app missing.

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#27]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

We need to give `BITBUCKET_CLIENT_ID` and `BITBUCKET_CLIENT_SECRET` in the `.env` file but there is no docs how to obtain them.

### Expected Behavior

There should be a `/docs`  folder.
It should have a `BITBUCKET_SETUP.md` containing steps to obtain  `BITBUCKET_CLIENT_ID` and `BITBUCKET_CLIENT_SECRET` .

### Additional Information

Also mention link to this file in the setup section of `README.md`

**Comment by Simran2337** [comment]
Can I take up this as a GSSOC participant?

**Comment by Shubham-Kumar-2000** [comment]
Sure go ahead @Simran2337
