### ISSUE TITLE
[Bug]: Github Setup for Oauth app missing

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#28]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

We need to give `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` in the `.env` file but there is no docs how to obtain them.

### Expected Behavior

There should be a /docs folder.
It should have a `GITHUB_SETUP.md` containing steps to obtain `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` .

### Additional Information

Also mention link to this file in the setup section of `README.md`

**Comment by Simran2337** [comment]
Can I take up this as a GSSOC participant?

**Comment by Shubham-Kumar-2000** [comment]
@Simran2337  please complete your assigned pr then re-comment to get assigned.

**Comment by amir-ammar** [comment]
Can i work on it ?

**Comment by Shubham-Kumar-2000** [comment]
Sure go  ahead @amir-ammar
