### ISSUE TITLE
[Feature Request]: Entry Barrier

### ISSUE THREAD

**Issue by AnshumanDubey1999** [open-certs/oc-backend#3]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

Anyone with a public repository and a few commits is able to generate a certificate.

### Proposed Solution

Create an entry barrier that allows only open-source repositories with some reputation to be used for creating certificates.

### Alternatives Considered

None

**Comment by MadhusreeBera** [comment]
Hello, I would like to contribute in this project. Please assign this issue

**Comment by Shubham-Kumar-2000** [comment]
Assigned go ahead.

**Comment by himanshusanecha** [comment]
I am interested to work upon this issue, but I have a doubt about how we will actually judge a repository and also the relevance of the contribution of the user.
