### ISSUE TITLE
[Bug]: Refactor clustering

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#32]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

All code related to clustering exists in `bin/www` file making it a total mess.

### Expected Behavior

Code related to clustering should be in `helpers/cluster.helper.js` which should be imported in `bin/www`. 
Thus streamlining the entire process.

**Comment by mdabdulshahed** [comment]
I want to work on this issue

**Comment by SatabrataPaul-GitAc** [comment]
Can you please assign this issue to me ?
I have completed my previous tasks 
Would like to work on this feature

**Comment by Shubham-Kumar-2000** [comment]
Sure @SatabrataPaul-GitAc  go ahead.

@mdabdulshahed  you still have pending PR so not assigning it to you.
