### ISSUE TITLE
[Bug]: Missing Gitlab Setup for Oauth app

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#36]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

We need to give `GITLAB_CLIENT_ID` and `GITLAB_CLIENT_SECRET` in the `.env` file but there is no docs how to obtain them.

### Expected Behavior

`/docs` folder should have a `GITLAB_SETUP.md` containing steps to obtain  `GITLAB_CLIENT_ID` and `GITLAB_CLIENT_SECRET` .

**Comment by Sukh0204** [comment]
Pls assign me this issue

**Comment by Shubham-Kumar-2000** [comment]
Sure go ahead @Sukh0204
