### ISSUE TITLE
[Feature Request]: Bitbucket Login

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#4]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

Bitbucket Login doesn't exist but many open source softwares are still maintained on Bitbucket.
Thus Bitbucket should be supported.

### Proposed Solution

We can use `passport-bitbucket-oauth2` as we are already using `passport`

### Alternatives Considered

None

**Comment by Kanika1309** [comment]
Hi...I am GSSoC'22 participant if this task is still open....please assign it to me.

**Comment by amir-ammar** [comment]
Hi...I am GSSoC'22 participant if this task is still open....please assign it to me.

**Comment by Shubham-Kumar-2000** [comment]
Ok Assigned
But Please raise the PR after 2nd March else it won't be counted.

**Comment by amir-ammar** [comment]
is there a discord channel to communicate through ?

**Comment by Shubham-Kumar-2000** [comment]
Yes its there but you will be able to see them from tomorrow I guess

**Comment by SatabrataPaul-GitAc** [comment]
If this task is still open , can you please assign it to me . I am a GSSOC'22 participant . 
I would like to make a contribution to this project
