### ISSUE TITLE
[Feature Request]: Gitlab Helper

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#42]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

No helper file present  to fetch `repo`, user's `commits`,  user's `pull_requests`, etc for a Gitlab repo.

### Proposed Solution

Create a `gitlab.helper.js` using [this package](https://www.npmjs.com/package/@gitbeaker/node).

Docs : https://github.com/jdalrymple/gitbeaker#readme

### Alternatives Considered

NA

### Additional Information

Follow the format of `github.helper.js`

**Comment by SatabrataPaul-GitAc** [comment]
Please assign this issue to me 
I want to work on it 
I have completed all previously assigned tasks

**Comment by Shubham-Kumar-2000** [comment]
Hi @SatabrataPaul-GitAc  complete the requested changes on your pr.

Then re-comment to get assigned.

**Comment by SatabrataPaul-GitAc** [comment]
I have completed the requested changes 
Kindly assign this issue to me

**Comment by Shubham-Kumar-2000** [comment]
Sure Assigned @SatabrataPaul-GitAc

**Comment by Shubham-Kumar-2000** [comment]
Hi @SatabrataPaul-GitAc  what's the update on this??

**Comment by SatabrataPaul-GitAc** [comment]
I will make the PR by today
Was working on it yesterday
Faced some issue
Can we get on a call tonight ?

**Comment by Shubham-Kumar-2000** [comment]
Sure no problem
