### ISSUE TITLE
[Feature Request]: Bitbucket Helper

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#43]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

No helper file present  to fetch `repo`, user's `commits`,  user's `pull_requests`, etc for a BitBucket repo.

### Proposed Solution

Create a `bitbucket.helper.js` using [this package](https://www.npmjs.com/package/bitbucket).

Docs : https://www.npmjs.com/package/bitbucket

### Alternatives Considered

NA

**Comment by Simran2337** [comment]
As a GSSOC'22 participant I want to work on this issue.
Can you please assign it to me.

**Comment by Shubham-Kumar-2000** [comment]
Sure go Ahead @Simran2337

**Comment by Shubham-Kumar-2000** [comment]
Hi @Simran2337  what's the update on the issue

**Comment by Shubham-Kumar-2000** [comment]
Un-assigning due to no response

**Comment by Simran2337** [comment]
Please reassign.

**Comment by Shubham-Kumar-2000** [comment]
Assigned
