### ISSUE TITLE
[Bug]: Randomly Failing test

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#44]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

Test `should return certificate details when valid certificate id is provided` randomly fails when there is no certificates already generated in the DB.

### Expected Behavior

This test should always create a new test certificate and test for that.

### Additional Information

NA

**Comment by Sukh0204** [comment]
Hello, please assign me this issue!

**Comment by Shubham-Kumar-2000** [comment]
Sure go head @Sukh0204

**Comment by Shubham-Kumar-2000** [comment]
Fixed by #48
