### ISSUE TITLE
[Bug]: Bitbucket issue, pr missing in scope

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#45]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

Currently PR and issues are missing for bitbucket Oauth scopes.

Both is code and docs.

### Expected Behavior

Scopes should be : 
```js
['repository', 'account', 'email', 'issue', 'pullrequest']
```

**Comment by Sukh0204** [comment]
Hello, Please assign me this issue.

**Comment by Shubham-Kumar-2000** [comment]
Sure go ahead @Sukh0204

**Comment by Shubham-Kumar-2000** [comment]
Hi @Sukh0204  what's the update on this issue

**Comment by Sukh0204** [comment]
Hello sir, Apologies for the delay, I'm working on the issue.
