### ISSUE TITLE
[Feature Request]: ReCaptchaError missing

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#52]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

When ever Re-captcha fails it should throw `CustomError`

### Proposed Solution

Ideally it should throw `ReCaptchaError` which extends `CustomError` for better error management.

### Alternatives Considered

NA

**Comment by MadhusreeBera** [comment]
please assign this issue to me

**Comment by Shubham-Kumar-2000** [comment]
Sure Go head. @MadhusreeBera
