### ISSUE TITLE
[Feature Request]: AuthError missing

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#53]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

When ever there is a authentication error api throws a `CustomError`.

### Proposed Solution

Instead it should throw a `AuthError` which extends the `CustomError` and has a extra field `logout: true` to tell the frontend to logout the user.

### Alternatives Considered

NA

**Comment by Vraj9799** [comment]
Hi @Shubham-Kumar-2000 I am a GSSOC Participant and would like to work on this improvement. Please assign it to me.

**Comment by Shubham-Kumar-2000** [comment]
Sure go ahead @VRAJ9799
