### ISSUE TITLE
[Bug]: Github error not formatting properlly

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#54]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

If there is any error from github api it comes as "Http-error..." which doesn't reveals anything.

### Expected Behavior

We should have a proper `GithubError` extending `CustomError` which properly formats the error and reveals intent.

**Comment by Sukriti-m** [comment]
Hi @Shubham-Kumar-2000 
I'd be grateful if you could assign this task to me under GSSOC'22.

**Comment by Shubham-Kumar-2000** [comment]
Sure go ahead @Sukriti-m

**Comment by Shubham-Kumar-2000** [comment]
Hi @Sukriti-m 
What's the update on this issue??

**Comment by Sukriti-m** [comment]
> Hi @Sukriti-m What's the update on this issue??

Sorry, I have not started it yet as I am unable to open it on my localhost due to some errors. The database is not getting connected.

**Comment by Shubham-Kumar-2000** [comment]
Hi @Sukriti-m can we connect on G-meet or some thing to solve this???

**Comment by Shubham-Kumar-2000** [comment]
Un-assigning due to no response

**Comment by sahilsuman933** [comment]
@Shubham-Kumar-2000 Can I work on this issue?

**Comment by iamppborah** [comment]
Hi @Shubham-Kumar-2000,
I would like to work on this issue, could you please assign me this task ?

**Comment by Shubham-Kumar-2000** [comment]
assigned @ppborah

**Comment by Shubham-Kumar-2000** [comment]
Closed by #74
