### ISSUE TITLE
[Bug]: Cross Provider access is not restricted

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#58]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

Once a user is authenticated, then it can access any user specific api.

But a user authenticated with `Github` should not be able to access `Gitlab` or `Bitbucket` specific apis.

### Expected Behavior

There should be a middleware in `provider.helper.js` which should take a `provider` as parameter and restricts the users accordingly.

### Additional Information

NA

**Comment by Sukh0204** [comment]
Hello, Please assign me this issue.

**Comment by Shubham-Kumar-2000** [comment]
Sure go ahead @Sukh0204

**Comment by Shubham-Kumar-2000** [comment]
@Sukh0204 any update on this??

**Comment by Shubham-Kumar-2000** [comment]
@Sukh0204 any update on this???

**Comment by Shubham-Kumar-2000** [comment]
Un-assigning due to no response

**Comment by Simran2337** [comment]
Assign this issue to me please!

**Comment by Shubham-Kumar-2000** [comment]
Sure go head
