### ISSUE TITLE
[Feature Request]: Last Contribution Date In Certificate

### ISSUE THREAD

**Issue by AnshumanDubey1999** [open-certs/oc-backend#6]
### Preflight Checklist

- [X] I have read the Contributions.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

The certificate doesn't show when the last contribution was made by the user.

### Proposed Solution

Add the last contribution date to the certificate.

### Alternatives Considered

None

**Comment by BishyanKar** [comment]
Let me handle it

**Comment by Kanika1309** [comment]
Hi...I am GSSoC'22 participant if this task is still open....please assign it to me.

**Comment by Shubham-Kumar-2000** [comment]
@Kanika1309 Please complete your assigned issue then re-comment to get it assigned to you.

**Comment by himanshusanecha** [comment]
Greetings,
Myself himanshu sanecha, recently got selected as a GSSOC participant. If this task is unassigned and open I want to contribute to this.

Some insights on how it will be implemented - 
1. Create a key-value pair in the certificate model to store the last contribution date.
2. getting the last commit of the user using octokit or using commits from getCommits to figure out the last commit and its date.
      a. For this we need to create a method in GitHub helpers to get the last commit of the user in the desired repo.
3. while creating the certificate just add a key-value pair of the last contribution date.

**Comment by Shubham-Kumar-2000** [comment]
Sure go ahead.

Just one more thing you need to show this on the certificate. In a human readable manner.

**Comment by himanshusanecha** [comment]
Yes for sure, will display it on the certificate.
