### ISSUE TITLE
[Bug]: CustomError should have a handleError() 

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#60]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

We are handling response for `CustomError` in the `errorhandler.helper.js` so in future if we multiple `CustomError` which needs to be handled differently then we will had to increase the if-else ladder in `errorhandler.helper.js`.

### Expected Behavior

`CustomError` should have a `handleError` which will take `res` as parameter and abstracts :

```js
res.status(err.status).json({
   error: err.getResponse()
});
```

And this `err.handleError(res)` should be called in  `errorhandler.helper.js`.

### Additional Information

NA

**Comment by Vraj9799** [comment]
Hi @Shubham-Kumar-2000 I would like to work on this bug.

I will add a new method in custom error which will take res as a parameter and from errorhandler.helper.js If an instance is of Custom Error I will call that method.

**Comment by Shubham-Kumar-2000** [comment]
Sure @VRAJ9799  goAhead.

Also don't forget to use `this.getResponse()` in `handleError`
