### ISSUE TITLE
[Bug]: Passport Error should be redirected to frontend

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [open-certs/oc-backend#63]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.0.1

### Current Behavior

Passport error is treated as a unexpected error and a JSON is displayed on the webpage.

### Expected Behavior

We should have a `PassportError` which extends `CustomError`.

And on `handleError` it should redirect it to frontend as :

```js
const url = new URL( `${process.env.FRONTEND_URL}/recievedToken.html`)
// put getResponse as query params
res.redirect(
    `${process.env.FRONTEND_URL}/recievedToken.html?errorType=.........`
);
```

### Additional Information

NA

**Comment by anipaul2** [comment]
I want to work on this issue. Assign me to this mentor.

**Comment by Shubham-Kumar-2000** [comment]
Sure goahead.
